KASH-517: Get authorization code from Square OAuth Api
Kashoo/classic-square-service pull request #1
Opened 2021-06-02 19:37 UTC by alvinlau

2021-06-02 19:38 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +  logger.info(`Request auth code for business ${req.body.businessId}`);
not sure if business will be in the request for this call

2021-06-02 20:42 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +const getAuth = catchAsync(async (req, res) => {
I don't know if the existing `createToken` method still makes sense to have around, or if you intended me to replace its definition.  Here I'm just making this `getAuth` method to be the first call, but we can reconcile.

2021-06-02 20:43 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +    <link type="text/css" rel="stylesheet" href="style.css">
this stylesheet is from the example, need to remove this usage for cleanup

2021-06-02 20:45 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +       href="${url}">
For our test accounts, when we press the button (calling the url), it just automatically authorizes.
Supposedly the real production one will prompt for user credentials, but I still need to manually try it to see for myself.

2021-06-02 20:46 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +    code: req.query,
Docs and example say it's in the query params, I'm curious if there's a specific param name, but the example does use `req.query`.  Another thing that needs to be verified by testing.

2021-06-02 20:49 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +if (process.env.SQUARE_ENVIRONMENT.toLowerCase() === 'production') {
copy-paste, just that there's the variable on environment and `squareClient` uses it, replacing the original usage of `Client`

2021-06-02 23:10 UTC, crockpotveggies requested changes

2021-06-02 23:10 UTC, crockpotveggies commented on .env.example
> +# Square OAuth2 configuration (defaults are for local dev)
Just keep in mind that this is an _example_ not the actual env required to run.

2021-06-02 23:10 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +  const content = `
Can we please make this JSON? i'm aware this is from the example, but i would like us to adapt it for our purposes instead of direct copy/paste. It's a microservice, so any UI should be in the tests for testing purposes.

2021-06-03 16:59 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +  const content = `
not relevant now that we're not making this call in this square service

2021-06-03 17:15 UTC, alvinlau commented
@crockpotveggies updated based on feedback - removed `getAuth` and `createToken` from prior code as `getAuth` is accomplished on frontend side that makes initial OAuth call to Square, and `obtainToken` outright does the same thing as `createToken` with returning the extracted token.

2021-06-03 18:36 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +  res.status(httpStatus.CREATED).send(JSON.parse(responseBody.body));
for some reason `responseBody.body` ends up being a string representation of json, I used `typeof` to check it too.

2021-06-03 18:37 UTC, crockpotveggies requested changes

2021-06-03 18:37 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +  res.status(httpStatus.CREATED).send(JSON.parse(responseBody.body));
that doesn't seem right, can you inspect the code and see if there's a different method you need to use? it might be `responseBody.json`

2021-06-03 18:45 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +  res.status(httpStatus.CREATED).send(JSON.parse(responseBody.body));
you're right, TLDR: it's `.result`

```
{"body":"{\n  \"access_token\": \"EAAAELdjXOlg1WmBVZJA-zICrOF9WblKaZ5d9Rujv46mgeiiQLCksJjqHEVWQzK9\",\n  \"token_type\": \"bearer\",\n  \"expires_at\": \"2021-07-03T18:41:35Z\",\n  \"merchant_id\": \"ML0B4EDYTD2SG\",\n  \"refresh_token\": \"EQAAEDrV7e_dYn5atc3rXU16A1OJTaao-8wLhKU3ufvJBx5RUbyx_3RpvEBK9uVt\",\n  \"short_lived\": false\n}",

"headers":{"access-control-allow-headers":"Content-Type, Authorization, Accept, X-Allow-Cookies, X-Block-Cookies","access-control-expose-headers":"Link","content-type":"application/json","square-version":"2021-05-13","vary":"Origin, Accept-Encoding","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"DENY","x-permitted-cross-domain-policies":"none","x-request-id":"Cgj1X2Nbh210SRABGBAiCQjQm4bmjvzwAg","x-xss-protection":"1; mode=block","date":"Thu, 03 Jun 2021 18:41:35 GMT","content-length":"299","strict-transport-security":"max-age=631152000; includeSubDomains; preload","connection":"close"},"statusCode":200,"request":{"method":"POST","url":"https://connect.squareupsandbox.com/oauth2/token","headers":{"user-agent":"Square-TypeScript-SDK/11.0.0","content-type":"application/json","Square-Version":"2021-05-13","accept":"application/json"},

"body":{"type":"text","content":"{\"client_id\":\"sandbox-sq0idb-hbUqEqDmurbeZX_QAKY21g\",\"client_secret\":\"sandbox-sq0csb-3I8VF_1pQ5Vj-PfYNCfzfoyn0obPqAjwVMJenby8anc\",\"code\":\"sandbox-sq0cgb-Ydkqj6VDYNcKx8GdAzMLNw\",\"grant_type\":\"authorization_code\",\"scopes\":[\"MERCHANT_PROFILE_READ\",\"PAYMENTS_READ\",\"SETTLEMENTS_READ\",\"ITEMS_READ\"]}"}},

"result":{"accessToken":"EAAAELdjXOlg1WmBVZJA-zICrOF9WblKaZ5d9Rujv46mgeiiQLCksJjqHEVWQzK9","tokenType":"bearer","expiresAt":"2021-07-03T18:41:35Z","merchantId":"ML0B4EDYTD2SG","refreshToken":"EQAAEDrV7e_dYn5atc3rXU16A1OJTaao-8wLhKU3ufvJBx5RUbyx_3RpvEBK9uVt","shortLived":false}}

2021-06-03 18:46 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +    code: req.query,
I think you're misreading the code here. This is a controller handling a request from the service's API. This means someone is POSTing the auth code as a JSON body to the square service. The docs are entirely different.

2021-06-04 21:54 UTC, crockpotveggies commented
One more thing: we personally don't need to handle `/receiveAuth`. Instead, the frontend will capture that, pass it to the gateway, and a request for `/obtain` will happen on our side. We then save the access token locally.

2021-06-04 21:55 UTC, crockpotveggies requested changes

2021-06-04 21:55 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +const receiveAuth = catchAsync(async (req, res) => {
We don't need this code in this microservice. The frontend will extract the authorization code for us. This is a backend service only.

2021-06-04 22:27 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +const receiveAuth = catchAsync(async (req, res) => {
great, even better!

2021-06-08 21:11 UTC, crockpotveggies requested changes

2021-06-08 21:11 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> -  const token = await Client.oAuthApi.obtainToken(requestBody);
We need to save this to the database in `obtainToken`

2021-06-09 22:57 UTC, crockpotveggies approved these changes

2021-06-09 22:58 UTC, merged