KASH-510: manual transactions sync
Kashoo/classic-square-service pull request #2
Opened 2021-06-10 22:40 UTC by alvinlau

2021-06-10 22:42 UTC, alvinlau commented on src/controllers/transactions.controller.js
> +  // get refunds
On one hand, it's the same code as calling payments, on the other hand, this is only the second time this code flow happens.  Maybe we can generalize this as `paginateSquareAPICall` or something on third time?

2021-06-10 22:43 UTC, alvinlau commented on tests/unit/models/token.model.test.js
> +const faker = require('faker');
Started some minimalistic model test, but then I realize there's not much to validate, since all the values are gotten from Square, it's not like they're entered by user/client and can screw up that way.

2021-06-10 22:44 UTC, alvinlau commented on src/controllers/transactions.controller.js
> +      squareResponse = await squareClient.paymentsApi.listPayments(startDate, undefined, 'DESC', paymentsCursor);
Not specifying `limit` now, since the default is 100 and that's they seems fine.  If we have to specify `limit`, then we have to add e.g. `undefined, undefined, undefined, undefined, 10` simply because there's other params in front of `limit` in the method defn.

2021-06-10 22:48 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +const squareClient = new Client({ environment: config.square.environment });
we already have this logic in our config, this if/else block was just adapted from example code previously, no need anymore.

2021-06-11 02:24 UTC, alvinlau commented on src/controllers/transactions.controller.js
> +      let startDate = moment(req.query.transactionStartDate).format('YYYY-MM-DD');
note to self: check `undefined` for `transactionStartDate`

2021-06-16 16:17 UTC, crockpotveggies requested changes
Overall, pretty good. Minor corrections so far.

2021-06-16 16:17 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +    res.status(httpStatus.NOT_FOUND).send();
Alternatively, you can throw an ApiError here. Might be cleaner so you can add a message and the client can interpret it.

2021-06-16 16:17 UTC, crockpotveggies commented on src/controllers/transactions.controller.js
> +      let startDate = moment(req.query.transactionStartDate).format('YYYY-MM-DD');
Yes make sure we supply this parameter.

2021-06-16 16:17 UTC, crockpotveggies commented on tests/integration/transactions.test.js
> +// const httpStatus = require('http-status');
Looks like this needs to be fleshed out. We'll want to ensure that tests account for pagination and transactionStartDate.

2021-06-16 21:18 UTC, alvinlau commented on src/models/transaction.model.js
> +const transactionSchema = mongoose.Schema(
I'm not including `lastUpdated` field here, since `transactionData.updatedAt` has the timestamp and we can maintain the time format from Square.  Next time we get a new `updatedAt` value from the next Square API call it will be easier to compare using same format.  Open to make it into explicit field in the model instead if appropriate.

2021-06-16 22:49 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +    res.status(httpStatus.NOT_FOUND).send();
really minor but I got stumped on this:
`ApiError` is defined in Square SDK and also by us in `utils/ApiError`
the `ApiError` always ends up being 500 so it broke my test that was expecting 404

at the end I went with adding the error text using our `ApirError` to keep things simple
```
res.status(httpStatus.NOT_FOUND).send('Token not found');
```

Otherwise we would have to explicitly refer to the specific `ApiError` we want to use in this file since we use both.
Or, just rename the `ApiError` class we made since it just inherits from `Error`

2021-06-17 21:03 UTC, crockpotveggies approved these changes

2021-06-17 21:47 UTC, merged