KASH-568: add catalog endpoint and starting implementation
Kashoo/classic-square-service pull request #3
Opened 2021-06-18 19:13 UTC by alvinlau

2021-06-22 10:11 UTC, alvinlau commented on src/controllers/transactions.controller.js
> +      squareResponse = await squareClient.paymentsApi.listPayments(startDate, undefined, 'ASC', paymentsCursor);
Felt we should change the order for transactions, doesn't matter too much in terms of correctness, but probably better to handle the older transactions first.  

This reminds me - I keep forgetting to say, maybe we should save the timestamp of the last successful batch run, perhaps specific to business, and we can use it as the default value for `transactionStartDate` if it's not specified in the url query params.  Maybe we can do this for the orders endpoint.

2021-06-23 00:12 UTC, alvinlau commented on src/controllers/tokens.controller.js
> +  // TODO check that code and businessID exist and are valid
went back to tokens controller and thought I want to add check here soon

2021-06-23 00:14 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +const webhookUpdate = catchAsync(async (req, res) => {
Square just gives as merchant id as the only indicator to identify the business.  So we get the access token via merchant id, and refresh their whole catalog.  Pretty much the same as the regular refresh route, except in /refresh it starts with business id and we get the access token from that.

2021-06-23 00:16 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +const updateCatalog = async (token) => {
Common method for given access token, call Square to get the catalog and save all the CatalogObjects to mongo.
Used by the manual /refresh call and also the /webhookUpdate

2021-06-23 18:03 UTC, crockpotveggies commented on src/controllers/transactions.controller.js
> +      squareResponse = await squareClient.paymentsApi.listPayments(startDate, undefined, 'ASC', paymentsCursor);
I would argue `DESC` is correct. It's also what the user will see first if they check their software. I would switch it back personally.

2021-06-23 18:13 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +  // TODO check that code and businessID exist and are valid
we can do a regex validation but calls to other services aren't necessary for the time being. lots of implementation with little reward, and it adds a dependency that breaks our "pure" service IMO

2021-06-23 18:14 UTC, crockpotveggies commented on src/controllers/tokens.controller.js
> +  // TODO check that code and businessID exist and are valid
There's a validation library built in to this repo. Let's get this implemented prior to merging.

2021-06-23 18:20 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +const updateCatalog = async (token) => {
I think right now we have a /transactions refresh call correct? I'd like to separate the catalog into its own route called `/catalog/<>/refresh`. The reason is to prevent extra data pulls and adding unnecessary load to the server. 

We can add a `/business/refresh` endpoint if necessary to refresh all objects.

2021-06-23 18:23 UTC, crockpotveggies requested changes

2021-06-23 18:23 UTC, crockpotveggies commented on src/controllers/transactions.controller.js
> +      throw new ApiError(httpStatus.INTERNAL_SERVER_ERROR, 'error in square response');
Can we add the error code to this message?

2021-06-23 18:23 UTC, crockpotveggies commented on src/models/catalog.object.model.js
> +catalogObjectSchema.statics.getObjectByObjectId = async (objectId) => {
What's an "object"? Are we storing a catalog in its entirety or is each object an item in a Mongo collection? I think we may need to optimize this.

2021-06-23 18:23 UTC, crockpotveggies commented on src/routes/v2/catalog.route.js
> +router
In my earlier comment I mentioned we need a route for this. Looks like you added it but this should be in a separate route file called `catalog.route.js`.

2021-06-23 18:23 UTC, crockpotveggies commented on tests/integration/catalog.test.js
> +});
Thank you for adding tests :)

2021-06-23 21:31 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +const updateCatalog = async (token) => {
@crockpotveggies that's exactly what's happening here, this is the catalog controller, it's just that the `/catalog/<business id>/refresh` route and the `/catalog/webhook/update` route both get all the catalog objects, and so extracted out that part as a helper method only within the catalog controller.

2021-06-23 21:35 UTC, alvinlau commented on src/models/catalog.object.model.js
> +catalogObjectSchema.statics.getObjectByObjectId = async (objectId) => {
it's a CatalogObject https://developer.squareup.com/reference/square/objects/CatalogObject.
Yes we're storing all the catalog objects for a business, in a mongo collection of CatalogObjects.  For now the code gets all the catalog objects without filtering out unneeded entries, but perhaps we may want to only keep item, tax, as such.  Those are all object types that can be returned as instances of catalog objects in the catalog for a business.

2021-06-23 21:39 UTC, alvinlau commented on src/routes/v2/catalog.route.js
> +router
oops, this file is `catalog.route.js`, just needed to rename a couple more instances of `transaction` > `catalog`

2021-06-23 23:49 UTC, crockpotveggies requested changes

2021-06-23 23:49 UTC, crockpotveggies commented on package.json
> +    "express-validator": "^6.11.0",
There's already a validator? Check dependency below. Why add another one?

2021-06-23 23:49 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +  logger.info(`got ${catalog.length} catalog objects total`);
Need to add a business and/or merchant ID in these logging statements or the logs don't have much context

2021-06-23 23:49 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +      logger.info(`failed to create or update catalog object ${object.objectId}`);
This needs to be a logger.error and include business/merchant ID

2021-06-23 23:49 UTC, crockpotveggies commented on tests/integration/catalog.test.js
> +  describe('POST /v2/catalog/{businessid}/refresh', () => {
Nitpick. businessid should be `businessId` camelCase with capital "i"

2021-06-24 00:56 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +        // no update for catalog object
just want to avoid spamming the logs for the catalog objects that didn't get upserted

2021-06-24 21:16 UTC, crockpotveggies requested changes

2021-06-24 21:16 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +  logger.info(`got ${catalog.length} catalog objects total`);
Still outstanding

2021-06-24 21:16 UTC, crockpotveggies commented on src/controllers/transactions.controller.js
> +      throw new ApiError(httpStatus.INTERNAL_SERVER_ERROR, `error in square response ${error}`);
Log the business or merchant ID please

2021-06-24 21:44 UTC, crockpotveggies requested changes

2021-06-24 21:44 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +      logger.info(`got ${objects.length} catalog objects for ${businessId} ${merchantId} cursor ${cursor}`);
we still need to identify what these numbers mean (applies to all other log statements too). when `${businessId}` is formatted, we will only see a random number we have to log `business ${businessId} merchant ${merchantId}`

2021-06-24 21:44 UTC, crockpotveggies commented on src/controllers/catalog.controller.js
> +  logger.info(`got ${catalog.length} catalog objects total for ${businessId} ${merchantId}`);
Same issue as above. Applies to all log statements.

2021-06-24 21:44 UTC, crockpotveggies commented on src/controllers/transactions.controller.js
> +    throw new ApiError(httpStatus.BAD_REQUEST, `valid transactionStartDate required for ${businessId}`);
`for business ${businessId}`

2021-06-24 23:11 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +  logger.info(`got ${catalog.length} catalog objects total`);
it's updated https://github.com/Kashoo/classic-square-service/pull/3/files#diff-6365a56daee0b1e5d3150de2f9e5ca8b46a498eb7fe97207eb00e48e3e62371eR52
github UI might be throwing you off here just because I didn't comment on it

2021-06-24 23:13 UTC, alvinlau commented on src/controllers/catalog.controller.js
> +      logger.info(`got ${objects.length} catalog objects for ${businessId} ${merchantId} cursor ${cursor}`);
agreed, I didn't do it for silly reason of keeping the line short, but js prettier formatter can help with that

2021-06-25 16:43 UTC, crockpotveggies approved these changes

2021-06-25 16:44 UTC, merged