KASH-578: create initial model and service for AccountMapping
Kashoo/classic-square-service pull request #4
Opened 2021-06-25 20:38 UTC by alvinlau

2021-06-25 20:39 UTC, alvinlau commented on src/models/account.mapping.model.js
> +  {
I looked in the sample json you gave me, here are all of the account fields
Up to you to say if we need to take out any, since there're so many, but likely they're all used if they were in the sample

2021-06-25 20:40 UTC, alvinlau commented on src/models/account.mapping.model.js
> +    taxes: { type: [taxSchema], required: true }, // should we make taxes required?
taxes as required array

2021-06-25 20:41 UTC, alvinlau commented on src/services/account.mapping.service.js
> +  let mapping = await AccountMapping.findOne({ merchantId: newMapping.id });
depending on the flow prior to calling this method, we could have either businessId (kashoo side) or merchantId (square side), we can switch to businessId if necessary.

2021-06-28 23:12 UTC, crockpotveggies requested changes

2021-06-28 23:12 UTC, crockpotveggies commented on src/models/account.mapping.model.js
> +    taxes: { type: [taxSchema], validate: (v) => Array.isArray(v) && v.length > 0 }, // should we make taxes required?
nitpick, can you format the line endings here?

2021-06-28 23:12 UTC, crockpotveggies commented on src/models/account.mapping.model.js
> +    third_party_card: {
No snake case please

2021-06-28 23:12 UTC, crockpotveggies commented on src/services/account.mapping.service.js
> +  let mapping = await AccountMapping.findOne({ merchantId: newMapping.id });
Side note: I think we need a memcache of the merchant -> business ID mapping

2021-06-28 23:13 UTC, crockpotveggies commented
@alvinlau we also need basic POST PATCH GET routes for viewing/saving mappings.

2021-06-29 00:01 UTC, alvinlau commented on src/models/account.mapping.model.js
> +    taxes: { type: [taxSchema], validate: (v) => Array.isArray(v) && v.length > 0 }, // should we make taxes required?
did you mean formatting the `taxes` block?
```
taxes: {
      type: [taxSchema],
      validate: (v) => Array.isArray(v) && v.length > 0,
    },
```
my editor and github itself is not showing any odd line ending characters, if that's what you mean

2021-06-29 00:18 UTC, alvinlau commented on src/services/account.mapping.service.js
> +  let mapping = await AccountMapping.findOne({ merchantId: newMapping.id });
small mistake - should be `merchantId: newMapping.merchantId` in this line, but we can also look up via `newMapping.businessId` the same way, we can just take whichever is available.

2021-06-29 09:43 UTC, alvinlau commented
`storeMapping` does upsert, and we can have `getMappingByBusinessId` and `getMappingByMerchantId`
I can create routes that connect POST PATCH GET to these methods respectively, what do you say?

2021-06-29 18:43 UTC, crockpotveggies approved these changes

2021-06-29 18:43 UTC, merged